### ISSUE TITLE
Toggle theme button not working on open ruler windows.

### ISSUE THREAD

**Issue by theo0165** [theo0165/floating-ruler#2]
When clicking the toggle theme button themes won't change on open rulers. Changes theme in background and when opening new ruler window.

Desired feature: When toggle theme is clicked, the theme on all open rulers will toggle and the theme in settings and be saved.

Tested on MacOS.

**Comment by chris--jones** [comment]
I can take this one on.

What's the min browser support required? because this sounds like a good candidate for css vars: https://caniuse.com/css-variables

**Comment by theo0165** [comment]
@chris--jones minimum requirements is [electron 14.0](https://www.electronjs.org/blog/electron-14-0/). They use [chromium 93](https://developer.chrome.com/blog/new-in-chrome-93/) and [v8 9.3](https://v8.dev/blog/v8-release-93) if im not mistaking.

Thanks!

**Comment by chris--jones** [comment]
ok cool, should be good then.

**Comment by chris--jones** [comment]
I got ahead of myself, it was just an issue with window cleanup.

**Comment by theo0165** [comment]
Fixed in #9
