### ISSUE TITLE
Pointer cursor not working on ruler window close button.

### ISSUE THREAD

**Issue by theo0165** [theo0165/floating-ruler#3]
Close button on ruler windows should have a pointer cursor. Currently only working on bottom of close button. Button is still functional but not UX friendly.

Close button can be found in [this](https://github.com/theo0165/floating-ruler/blob/main/src/app/ruler/ruler.html) file. DIV element with class `.close_btn`.

**Comment by NeoIsRecursive** [comment]
I can try and solve this

**Comment by theo0165** [comment]
Issue fixed on win32 branch. Pull request #8
